comment:
  active: 'false'
complexmethod:
  active: 'true'
  threshold: '10'
cycle:
  active: 'true'
dataclass:
  active: 'true'
deadcode:
  active: 'true'
featureenvy:
  active: 'true'
  ignoreStatic: 'false'
  threshold: '0.52'
  base: '0.5'
  weight: '0.5'
godclass:
  active: 'true'
  wmc: '47'
  atfd: '5'
  tcc: '0.33'
largeclass:
  active: 'true'
  threshold: '150'
longmethod:
  active: 'true'
  threshold: '20'
longparameterlist:
  active: 'true'
  threshold: '5'
middleman:
  active: 'true'
  threshold: 'half'
messagechain:
  active: 'true'
  threshold: '3'
metrics:
  active: 'false'
  skipCC_CM: 'true'
